# Generated by Django 2.1 on 2018-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='имя')),
                ('image', models.ImageField(blank=True, help_text='выберите картинку для слайда', upload_to='sliders_images/', verbose_name='картинка продукта')),
                ('description', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='содержание слайда')),
                ('link', models.CharField(blank=True, default='#featured-services', max_length=128, null=True, verbose_name='ссылка если нужна')),
                ('is_active', models.BooleanField(default=True, verbose_name='добавить для вывода на основной странице?')),
                ('active_slide', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='активный ли это слайд (внимание написать active только для первого слайда в остальных случаях пустое значение)')),
            ],
            options={
                'verbose_name': 'слайд',
                'verbose_name_plural': 'слайды',
            },
        ),
        migrations.CreateModel(
            name='time_acceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name=' примечание ')),
                ('label_time', models.DateTimeField(verbose_name='время начала приемов ')),
                ('is_active', models.BooleanField(default='True', verbose_name='включить этот прием? ')),
                ('FIO', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name=' ФИО клиента ')),
                ('email', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name=' эл почта ')),
                ('tel', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='контактный тел. ')),
            ],
            options={
                'verbose_name': 'время приема',
                'verbose_name_plural': 'время приемов',
            },
        ),
        migrations.CreateModel(
            name='time_acceptance_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=164, null=True, verbose_name='название периода можно не заполнять')),
                ('time_lable_one', models.DateTimeField(verbose_name='время начала приемов ')),
                ('time_lable_two', models.DateTimeField(verbose_name=' время окончания приемов')),
                ('ot', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='час начало приемов: написать 9 если с  09:00, 10 если с 10:00')),
                ('do', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='час окончаиния приемов: написать 18 если с  18:00, 19 если с 19:00')),
                ('obed_one', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='час начала обеда')),
                ('obed_two', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='час окончаиния обеда')),
                ('period', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='период дробление времени одного приема, писать в секундах 3600 = 1 час, 1800 = 0.5 часа ')),
                ('is_active', models.BooleanField(default='True', verbose_name='включить этот генератор? ')),
            ],
            options={
                'verbose_name': 'генератор приемов',
                'verbose_name_plural': 'генератор приемов',
            },
        ),
    ]
