# Generated by Django 2.1 on 2018-08-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0005_useful_little_things'),
    ]

    operations = [
        migrations.AddField(
            model_name='useful_little_things',
            name='name_english',
            field=models.CharField(blank=True, default=None, max_length=1028, null=True, verbose_name='имя мелочи на английском для фильтра'),
        ),
        migrations.AlterField(
            model_name='useful_little_things',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1028, null=True, verbose_name='имя мелочи'),
        ),
    ]
