# Generated by Django 2.1 on 2018-08-09 09:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0006_auto_20180809_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='useful_little_things',
            name='descrip',
            field=models.CharField(blank=True, default=None, max_length=1028, null=True, verbose_name='описание обычным текстом'),
        ),
        migrations.AlterField(
            model_name='useful_little_things',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='описание позволяющие наполнять HTML разметку'),
        ),
    ]
