# Generated by Django 2.1 on 2018-08-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0007_auto_20180809_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(blank=True, help_text='выберите картинку для инфо о нас', upload_to='sliders_images/', verbose_name='картинка для информации о нас'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1028, null=True, verbose_name='имя информации'),
        ),
    ]
