# Generated by Django 2.1 on 2018-09-25 06:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0008_auto_20180809_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='имя статьи кратко это будет в меню навигации')),
                ('description', tinymce.models.HTMLField(blank=True, default='', max_length=64, null=True, verbose_name=' все описание статьи можно вставлять код html целиком')),
                ('is_active', models.BooleanField(default='True', verbose_name=' выложить статью на сайт ')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.AddField(
            model_name='slide',
            name='button_text',
            field=models.CharField(blank=True, default='посмотреть сайт', max_length=128, null=True, verbose_name='текст кнопки в слайдере'),
        ),
        migrations.AddField(
            model_name='time_acceptance_period',
            name='holiday1',
            field=models.CharField(blank=True, default='None', max_length=25, null=True, verbose_name='первый выходной писать цифрой (дни недели понедельник это 0, вторник это 1 и т.д.) Внимание если вы работаете и по выходным вписать 7'),
        ),
        migrations.AddField(
            model_name='time_acceptance_period',
            name='holiday2',
            field=models.CharField(blank=True, default='None', max_length=25, null=True, verbose_name='второй выходной писать цифрой (дни недели понедельник это 0, вторник это 1 и т.д.) Внимание если вы работаете и по выходным вписать 7'),
        ),
        migrations.AddField(
            model_name='time_acceptance_period',
            name='is_active2',
            field=models.BooleanField(default='True', verbose_name='включить две метки на главную страницу? '),
        ),
        migrations.AlterField(
            model_name='time_acceptance',
            name='is_active',
            field=models.BooleanField(default='True', verbose_name='включить этот прием для генерирования времен приема? '),
        ),
        migrations.AlterField(
            model_name='time_acceptance_period',
            name='is_active',
            field=models.BooleanField(default='True', verbose_name='включить этот генератор? внимание после окончания генерирования выключить эту галку '),
        ),
    ]
