# Generated by Django 2.1 on 2018-09-25 12:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0009_auto_20180925_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(blank=True, help_text='выберите картинку для слайда', upload_to='sliders_images/', verbose_name='картинка для информации о нас'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1028, null=True, verbose_name='имя услуги'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name=' все описание статьи можно вставлять код html целиком'),
        ),
    ]
