# Generated by Django 2.1 on 2018-09-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0010_auto_20180925_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='sertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name=' ')),
                ('image', models.ImageField(blank=True, help_text='выберите картинку для сертификата', upload_to='sertification_images/', verbose_name='картинка слайда')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
