# Generated by Django 2.1 on 2018-09-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0011_sertification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertification',
            name='is_active',
            field=models.BooleanField(default='True', verbose_name=' выложить сертификат на сайт '),
        ),
        migrations.AlterField(
            model_name='sertification',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='название серитфиката'),
        ),
    ]
